name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    container: opensuse/tumbleweed

    steps:
      - run: zypper -n install
              python3-flake8
              python3-flake8-builtins
              python3-flake8-bugbear
              python3-flake8-import-order
              python3-flake8-quotes

      - uses: actions/checkout@v2

      - run: flake gcc-bisect.py usage-wrapper.py
